
AWSTemplateFormatVersion: 2010-09-09
Parameters:
    FullDomainName:
        AllowedPattern: (?!-)[a-zA-Z0-9-.]{1,63}(?<!-)
        Description: The full unique domain name e.g. www.example.com
        Type: String


Resources:
    S3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: !Ref FullDomainName
        AccessControl: PublicRead
        WebsiteConfiguration:
            IndexDocument: index.html
            ErrorDocument: error.html
    BucketPolicy:
        Type: AWS::S3::BucketPolicy
        Properties:
          Bucket: !Ref S3Bucket
          PolicyDocument:
            Statement:
                - 
                  Effect: Allow
                  Principal: '*'
                  Action: 's3:GetObject'
                  Resource: !Join
                    - ''
                    - - 'arn:aws:s3:::'
                      - !Ref S3Bucket
                      - '/*'

Outputs:
    WebsiteURL:
      Value: !GetAtt
        - S3Bucket
        - WebsiteURL 
      Description: URL for website hosted on S3   
    S3BucketSecureURL:
      Value: !Join
        - ''
        - - 'https://'
          - !GetAtt
            - S3Bucket
            - DomainName
      Description: Name of S3 bucket to hold website content
    
